language: python
sudo: false

install: "pip install -r requirements.txt"

script: 
  - git clone https://github.com/ossec/ossec.github.io _build/html/
  - make html

after_success:
  - (cd _build/html/ && git add . && git commit -m "deployed to github pages" &&  git config user.email travis-ci@travis && git config user.name  "Travis-CI" && git push --force --quiet https://$GH_TOKEN@github.com/ossec/ossec.github.io.git)
